<?php
/**
 * @version		1.0.0 Templatebuilder $
 * @package		Templatebuilder
 * @copyright	Copyright © 2012 - All rights reserved.
 * @license		GNU/GPL
 * @author		Nate Mason
 * @author mail	nate@fargodesignco.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

// Your custom code here

$document = JFactory::getDocument ();

$document->addScript("http://cdn.jquerytools.org/1.2.7/full/jquery.tools.min.js");
$document->addScript("components/com_templatebuilder/assets/javascript/fancyselect.js");
$document->addScript("components/com_templatebuilder/assets/javascript/chosen.jquery.js");
$document->addScript("components/com_templatebuilder/assets/javascript/functions.js");
$document->addStylesheet("components/com_templatebuilder/assets/css/chosen.css");
$document->addStylesheet("components/com_templatebuilder/assets/css/form.css");


$categories = $this->categories;
$agencies = $this->agencies;
$types = $this->types;
$roles = $this->roles;


//echo "<pre>";print_r($roles); echo "</pre>";

?>

<form method="post" enctype="multipart/form-data" action="<?php echo JRoute::_("index.php") ?>" id="addForm">
	<div id="content">
		<div id="header">
			
			<h2>Please fill out the required fields below:</h2>
		</div>
		<div style="clear:both"></div>
		<div id="wrapper">
			<div id="content_top">
				<div id="content_left">
					<h2>RESOURCE TITLE</h2>
					<div>
						<input type="text" name="title"  />
					</div>
				</div>
				<div id="content_right">
					<h3>My role is a:</h3>
					<select name="roles" id="roles">
						<? foreach($roles as $t){?>
						<option value="<?php echo $t->id ?>"><?php echo $t->title ?></option>
						<? } ?>
					</select>
				</div>
			</div>
			<div id="content_middle">
				<div id="content_left">
				<h3>SELECT RELATED CATEGORIES <span>(check all that apply)</span></h3>
				<select name="categories[]" multiple="multiple" class="chzn-select-deselect">
					<?php 
				foreach($categories as $k){
					?>
					<option value="<?php echo $k->id ?>">
					<?php echo $k->title ?>
					</option>
					<?php if($k->hasChildren()){ 
						    	$arr = $k->getChildren();
								foreach($arr as $a){ ?>
					<option value="<?php echo $a->id ?>">
					<?php echo $a->title ?>
					</option>
					<?
								}
						} ?>
					<?
				}
			?>
				</select>
				</div>
				
				
				<div id="content_right">
					<h3>SELECT RELATED AGENCIES <span>(check all that apply)</span></h3>
					<select name="agencies[]" multiple="multiple" class="chzn-select-deselect">
						<?php 
							foreach($agencies as $k){
								?>
						<option value="<?php echo $k->id ?>">
						<?php echo $k->title ?>
						</option>
						<?php if($k->hasChildren()){ 
											$arr = $k->getChildren();
											foreach($arr as $a){ ?>
												<option value="<?php echo $a->id ?>"><?php echo $a->title ?></option>
						<?
											}
									} ?>
						<?
							}
						?>
					</select>
				</div>
				
				<div style="clear:both"></div>
			</div>
			<div id="bottom_content">
			
			
			
				<div class="upload_file">
					<h3>UPLOAD YOUR FILE</h3>
					<div class="file-wrapper">
						<input type="file"  name="filename"/>
						<span class="file-holder">Choose a File</span><span class="button">Browse</span></div>
					<div style="clear:both"></div>
				</div>
	
				
			<div style="clear:both"></div>
			
			
			<div id="foot">
				<h3>DESCRIPTION <span>(up to 1000 words)</span></h3>
				<textarea name="desc" cols="20" rows="20"></textarea>
			</div>
			
			
			
			
			
			
				<?php /*?><div class="agencies">
					<h3>SELECT RELATED AGENCIES <span>(check all that apply)</span></h3>
					<select name="agencies" multiple="multiple" class="chzn-select-deselect">
						<?php 
							foreach($agencies as $k){
								?>
						<option value="<?php echo $k->id ?>">
						<?php echo $k->title ?>
						</option>
						<?php if($k->hasChildren()){ 
											$arr = $k->getChildren();
											foreach($arr as $a){ ?>
												<option value="<?php echo $a->id ?>"><?php echo $a->title ?></option>
						<?
											}
									} ?>
						<?
							}
						?>
					</select>
				</div><?php */?>
				
				<div style="clear:both"></div>
			</div>
			<?php /*?><div id="foot">
				<h3>DESCRIPTION <span>(up to 1000 words)</span></h3>
				<?php
				$editor =& JFactory::getEditor();
				echo $editor->display( 'desc', '', '737', '87', '20', '20', false);
			
			?>
			</div><?php */?>
		</div>
		<div class="buttons">
			<input type="submit" id="submit" value= ' '/>
			<input type="reset" id="reset" value=' '/>
			<div style="clear:both"></div>
		</div>
	</div>
	<input type="hidden" name="type" value="<?php echo $types->id ?>">
	<input type="hidden" name="option" value="<?php echo JRequest::getVar( 'option' );?>"/>
	<input type="hidden" name="view" value="<?php echo JRequest::getVar( 'view' ,"templates");?>"/>
	<input type="hidden" name="task" value="save"/>
	<input type="hidden" name="dshare_task" value="insert"/>
	<input type="hidden" name="format" value="raw">
	<input type="hidden" name="referrer" value="<?php echo $_SERVER['HTTP_REFERER']; ?>" />
</form>
