<?php
/**
 * @version		1.0.0 Templatebuilder $
 * @package		Templatebuilder
 * @copyright	Copyright © 2012 - All rights reserved.
 * @license		GNU/GPL
 * @author		Nate Mason
 * @author mail	nate@fargodesignco.com
 *
 *
 * @MVC architecture generated by MVC generator tool at http://www.alphaplug.com
 */

// no direct access
defined('_JEXEC') or die('Restricted access');

jimport( 'joomla.application.component.view' );

class TemplatebuilderViewTemplates extends Jview
{
	function display($tpl = null){
		// global $mainframe;
		$model = $this->getModel();
		
		$params = TemplatebuilderHelper::getParams();
		$items = $model->getTemplates();
		$this->assignRef("items",$items);
		parent::display($tpl);

	}
	
	
	function details($tpl = null){
		// global $mainframe;
		$model = $this->getModel();
		
		$params = TemplatebuilderHelper::getParams();
		$item = $model->getTemplate(JRequest::getVar("id",false));
		$this->assignRef("item",$item);
		parent::display($tpl);

	}
	
	
	function add($tpl = null){
		// global $mainframe;
		$model = $this->getModel();
		
		$params = TemplatebuilderHelper::getCompParams();
		$cat = TemplatebuilderHelper::getCategory(56);
		$this->assignRef("roles",$cat->getChildren());
		$cat = TemplatebuilderHelper::getCategory(19);
		$this->assignRef("agencies",$cat->getChildren());
		$cat = TemplatebuilderHelper::getCategory(61);
		$types= $cat;
		$this->assignRef("types",$types);
		$cat = TemplatebuilderHelper::getCategory(54);
		$this->assignRef("categories",$cat->getChildren());
		parent::display($tpl);

	}

}
?>